/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:de51ed19-969b-433a-b63d-4e40f32e0023",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_MP9smgWYN",
    "aws_user_pools_web_client_id": "5r1vca186oef9fb2gpdppqc5pa",
    "oauth": {}
};


export default awsmobile;
